name: Demo push with tags
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Lokalise
        uses: lokalise/lokalise-push-action@main
        id: lokalise-push
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 2853102668763e85e45176.50644855
          base_lang: en
          translations_path: |
            en.lproj
          file_format: strings
          name_pattern: "*.strings"
          # rambo_mode: false
          # skip_tagging: true
          # use_tag_tracking: false
          # name_pattern: "en/**/custom_*.json"
          

      - name: Debug Outputs
        run: |
          echo "Initial Run: ${{ steps.lokalise-push.outputs.initial_run }}"
          echo "Files Uploaded: ${{ steps.lokalise-push.outputs.files_uploaded }}"